-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 16:08:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema psiprojekat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psiprojekat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psiprojekat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `psiprojekat` ;

-- -----------------------------------------------------
-- Table `psiprojekat`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`salon` (
  `salonId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(100) NOT NULL,
  `working_hours` VARCHAR(50) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `grade` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`salonId`),
  UNIQUE INDEX `userId_UNIQUE` (`salonId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `price` FLOAT NOT NULL,
  `duration` INT NOT NULL,
  `salonId` INT NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idService`),
  UNIQUE INDEX `idService_UNIQUE` (`idService` ASC) VISIBLE,
  UNIQUE INDEX `salonId_UNIQUE` (`salonId` ASC) VISIBLE,
  CONSTRAINT `service_salon_fk`
    FOREIGN KEY (`salonId`)
    REFERENCES `psiprojekat`.`salon` (`salonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`user` (
  `useriId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`useriId`),
  UNIQUE INDEX `useriId_UNIQUE` (`useriId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`staff` (
  `userId` INT NOT NULL,
  `salonId` INT NOT NULL,
  `position` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`position`, `userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `salonId_UNIQUE` (`salonId` ASC) VISIBLE,
  INDEX `staff_user_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `staff_salon_fk_idx` (`salonId` ASC) VISIBLE,
  CONSTRAINT `staff_salon_fk`
    FOREIGN KEY (`salonId`)
    REFERENCES `psiprojekat`.`salon` (`salonId`)
    ON UPDATE CASCADE,
  CONSTRAINT `staff_user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `psiprojekat`.`user` (`useriId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`appointment` (
  `appointmentId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `staffId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`appointmentId`),
  UNIQUE INDEX `appointmentId_UNIQUE` (`appointmentId` ASC) VISIBLE,
  UNIQUE INDEX `userid_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `staffId_UNIQUE` (`staffId` ASC) VISIBLE,
  UNIQUE INDEX `serviceId_UNIQUE` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `appoitment_services_fk`
    FOREIGN KEY (`serviceId`)
    REFERENCES `psiprojekat`.`service` (`idService`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `appoitment_staff_fk`
    FOREIGN KEY (`staffId`)
    REFERENCES `psiprojekat`.`staff` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `appoitment_user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `psiprojekat`.`user` (`useriId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`notification` (
  `notificationId` INT NOT NULL AUTO_INCREMENT,
  `appointmentId` INT NOT NULL,
  `userId` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `sendAt` DATETIME NULL DEFAULT NULL,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`notificationId`),
  UNIQUE INDEX `notificationId_UNIQUE` (`notificationId` ASC) VISIBLE,
  UNIQUE INDEX `appoitmentId_UNIQUE` (`appointmentId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `notification_appointment_fk`
    FOREIGN KEY (`appointmentId`)
    REFERENCES `psiprojekat`.`appointment` (`appointmentId`)
    ON UPDATE CASCADE,
  CONSTRAINT `notification_user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `psiprojekat`.`user` (`useriId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`owner` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `salonId` INT NOT NULL,
  `verified` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `salonId_UNIQUE` (`salonId` ASC) VISIBLE,
  INDEX `owner_salon_fk_idx` (`salonId` ASC) VISIBLE,
  CONSTRAINT `owner_salon_fk`
    FOREIGN KEY (`salonId`)
    REFERENCES `psiprojekat`.`salon` (`salonId`)
    ON UPDATE CASCADE,
  CONSTRAINT `owner_user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `psiprojekat`.`user` (`useriId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `psiprojekat`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psiprojekat`.`review` (
  `reviewId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `salonId` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`reviewId`),
  UNIQUE INDEX `reviewId_UNIQUE` (`reviewId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `salonId_UNIQUE` (`salonId` ASC) VISIBLE,
  CONSTRAINT `review_salon_fk`
    FOREIGN KEY (`salonId`)
    REFERENCES `psiprojekat`.`salon` (`salonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `review_user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `psiprojekat`.`user` (`useriId`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
