# Generated by Django 6.0.2 on 2026-02-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='appointmentId', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='dateTime')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('useriid', models.AutoField(db_column='useriId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('salonid', models.AutoField(db_column='salonId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=45)),
                ('grade', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salon',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='notificationId', primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('sendat', models.DateTimeField(blank=True, db_column='sendAt', null=True)),
                ('type', models.IntegerField()),
                ('appointmentid', models.ForeignKey(db_column='appointmentId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.appointment')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='userid',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(db_column='reviewId', primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.user')),
                ('salonid', models.ForeignKey(db_column='salonId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.salon')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservice', models.AutoField(db_column='idService', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('salonid', models.ForeignKey(db_column='salonId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.salon')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.service'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(db_column='staffId', primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=30)),
                ('salonid', models.ForeignKey(db_column='salonId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.salon')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.user')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='staffid',
            field=models.ForeignKey(db_column='staffId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.staff'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('legacy_user', models.OneToOneField(db_column='legacy_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='appIva.user')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appIva.user')),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('salonid', models.ForeignKey(db_column='salonId', on_delete=django.db.models.deletion.DO_NOTHING, to='appIva.salon')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
