# Generated by Django 6.0.1 on 2026-03-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appIva.user')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'google_calendar_connection',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
